### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rezackacz** [tijayfly/ets-tacc-git#3]
When i am trying to run this, im getting this error: 

> Traceback (most recent call last):
>   File "tacc.py", line 138, in <module>
>     label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
>   File "C:\Users\Jáchym\AppData\Roaming\Python\Python38\site-packages\object_detection\utils\label_map_util.py", line 168, in load_labelmap
>     label_map_string = fid.read()
>   File "C:\Program Files\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
>     self._preread_check()
>   File "C:\Program Files\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
>     self._read_buf = _pywrap_file_io.BufferedInputStream(
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 134: invalid continuation byte
>

**Comment by tijayfly** [comment]
This has probably been answered in the Youtube comments. Failing that, repeat the install process

**Comment by tijayfly** [comment]
Archiving project, please use default acc + easypilot or lane assist by other developers
